import CatalogListing from '@/app/Components/CatalogListing'
import React from 'react'

export const metadata = {
    title: "Mens | MayBell - Online Store",
    description: "Generated by create next app",
};

export default function page() {

  return (
    <>
        <CatalogListing/>
    </>
  )
}
