import React from 'react'
import CatalogListing from '../Components/CatalogListing';

export const metadata = {
    title: "Catalog | MayBell - Online Store",
    description: "Generated by create next app",
};

export default function page() {
    return (
        <>
            <CatalogListing/>
        </>
    )
}
